# Generated by Django 5.2.3 on 2026-02-11 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('phase', models.CharField(max_length=50)),
                ('zone_a_count', models.IntegerField(default=0)),
                ('zone_b_count', models.IntegerField(default=0)),
                ('zone_c_count', models.IntegerField(default=0)),
                ('zone_d_count', models.IntegerField(default=0)),
                ('zone_e_count', models.IntegerField(default=0)),
                ('zone_f_count', models.IntegerField(default=0)),
                ('green_time', models.IntegerField(default=0)),
                ('total_vehicles', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrafficStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_cycles', models.IntegerField(default=0)),
                ('total_vehicles', models.IntegerField(default=0)),
                ('avg_green_time', models.FloatField(default=0.0)),
                ('avenida_ida_cycles', models.IntegerField(default=0)),
                ('avenida_vuelta_cycles', models.IntegerField(default=0)),
                ('intersection_a_cycles', models.IntegerField(default=0)),
                ('intersection_d_cycles', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='TrafficRecord',
        ),
    ]
